# Generated by Django 5.1.3 on 2024-11-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('cod_disciplina', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome_disciplina', models.CharField(default='', max_length=100)),
                ('carga_horaria', models.IntegerField(default=0)),
                ('periodo', models.IntegerField(default=0)),
            ],
        ),
    ]
