# Generated by Django 5.1.3 on 2024-12-04 14:47

import rest_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=200)),
                ('cpf', models.CharField(max_length=11, validators=[rest_api.models.validar_cpf])),
            ],
        ),
    ]
