# Generated by Django 5.1.3 on 2024-12-11 14:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="O formato do semestre deve ser 'xxxx-xx'.", regex='^\\d{4}-\\d{2}$')])),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='rest_api.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='AlunoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='rest_api.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='rest_api.turma')),
            ],
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('disciplina', 'semestre'), name='unique_disciplina_semestre'),
        ),
        migrations.AlterUniqueTogether(
            name='alunoturma',
            unique_together={('aluno', 'turma')},
        ),
    ]
