# Generated by Django 5.1.3 on 2025-01-08 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_turma_alunoturma_turma_unique_disciplina_semestre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="O formato do CPF deve ser 'xxx.xxx.xxx-xx'.", regex='^\\d{3}.\\d{3}.\\d{3}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='periodo',
            field=models.CharField(default='', max_length=5),
        ),
    ]
