# Generated by Django 5.1.3 on 2025-01-22 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_alter_aluno_cpf_alter_disciplina_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='rest_api.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='rest_api.turma')),
            ],
        ),
    ]
