# Generated by Django 5.1.3 on 2025-01-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_alter_nota_aluno_alter_nota_final_alter_nota_nota1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='rest_api.aluno'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='rest_api.turma'),
        ),
    ]
