# Generated by Django 5.1.3 on 2025-01-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_alter_nota_aluno_alter_nota_turma'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('aluno', 'turma'), name='unique_aluno_turma_nota'),
        ),
    ]
