# Generated by Django 5.1.3 on 2025-01-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_nota_unique_aluno_turma_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='_status',
            field=models.CharField(default='PENDENTE', max_length=20),
        ),
    ]
