# Generated by Django 5.1.3 on 2024-11-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_usuario', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('login_usuario', models.CharField(default='', max_length=100)),
                ('senha_usuario', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
